// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqougrrpobzemkumlrao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxb3VncnJwb2J6ZW1rdW1scmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzM2NTIsImV4cCI6MjA3MDYwOTY1Mn0.EZxMtNJAWsSVWMPGh8ka6ANwk0ebb-8zQ0AYWwcPYjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});